-- Añadir campos para el sistema de premios
ALTER TABLE league_config 
  ADD COLUMN IF NOT EXISTS entry_fee NUMERIC NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS prize_div1_1st NUMERIC NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS prize_div1_2nd NUMERIC NOT NULL DEFAULT 16,
  ADD COLUMN IF NOT EXISTS prize_div1_3rd NUMERIC NOT NULL DEFAULT 11,
  ADD COLUMN IF NOT EXISTS prize_div2_1st NUMERIC NOT NULL DEFAULT 14,
  ADD COLUMN IF NOT EXISTS prize_div2_2nd NUMERIC NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS prize_div2_3rd NUMERIC NOT NULL DEFAULT 8,
  ADD COLUMN IF NOT EXISTS prize_div3_1st NUMERIC NOT NULL DEFAULT 8,
  ADD COLUMN IF NOT EXISTS prize_div3_2nd NUMERIC NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS prize_div3_3rd NUMERIC NOT NULL DEFAULT 3;
